name: ntb
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0  # Cập nhật lên phiên bản mới nhất
  firebase_auth: ^5.5.2  # Cập nhật lên phiên bản mới nhất
  google_sign_in: ^6.1.5
  cloud_firestore: ^5.6.6  # Cập nhật lên phiên bản mới nhất
  provider: ^6.1.4
  intl: ^0.18.0
  share_plus: ^7.0.0
  badges: ^3.0.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
