// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpuGMn9SxHqd3wc5-162ViwaMkzLQ6y58',
    appId: '1:639819162925:web:2388d3c5dec1ff3bcc1fa4',
    messagingSenderId: '639819162925',
    projectId: 'my-app-ntb-b98b7',
    authDomain: 'my-app-ntb-b98b7.firebaseapp.com',
    storageBucket: 'my-app-ntb-b98b7.firebasestorage.app',
    measurementId: 'G-J687XCFZ4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4GNFEtJk0DjQzKVX2tiTE2iz5YwVBeiM',
    appId: '1:639819162925:android:583c2e873252a688cc1fa4',
    messagingSenderId: '639819162925',
    projectId: 'my-app-ntb-b98b7',
    storageBucket: 'my-app-ntb-b98b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDysqHpBTWhSDQcC0UWmMhaK8A8mp888cg',
    appId: '1:639819162925:ios:8372a26310004289cc1fa4',
    messagingSenderId: '639819162925',
    projectId: 'my-app-ntb-b98b7',
    storageBucket: 'my-app-ntb-b98b7.firebasestorage.app',
    androidClientId: '639819162925-i9cs27r6bf63muj821b8qbkrtj6afj16.apps.googleusercontent.com',
    iosClientId: '639819162925-aliooj22rtigh4iun6maot2pjadoruhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.ntb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDysqHpBTWhSDQcC0UWmMhaK8A8mp888cg',
    appId: '1:639819162925:ios:8372a26310004289cc1fa4',
    messagingSenderId: '639819162925',
    projectId: 'my-app-ntb-b98b7',
    storageBucket: 'my-app-ntb-b98b7.firebasestorage.app',
    androidClientId: '639819162925-i9cs27r6bf63muj821b8qbkrtj6afj16.apps.googleusercontent.com',
    iosClientId: '639819162925-aliooj22rtigh4iun6maot2pjadoruhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.ntb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpuGMn9SxHqd3wc5-162ViwaMkzLQ6y58',
    appId: '1:639819162925:web:51f78d23caed42a1cc1fa4',
    messagingSenderId: '639819162925',
    projectId: 'my-app-ntb-b98b7',
    authDomain: 'my-app-ntb-b98b7.firebaseapp.com',
    storageBucket: 'my-app-ntb-b98b7.firebasestorage.app',
    measurementId: 'G-2PSVHB6WEN',
  );

}